---
- name: ansible project
  hosts: prod
  remote_user: ec2-user
  become: yes
  tasks:
   - name:  war file
     copy:
       src:  target/wwp-1.0.0.war
       dest: /var/lib/tomcat9/webapps/wwp-1.0.0.war
       owner: tomcat9
       group: tomcat9
